version: '3.9'

services:
  server:
    build: .
    ports:
      - '3000:3000'
  db:
    image: 'postgres'
    ports:
      - '5232:5232'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'Docker'
